name: Deploy to Render

on:
  push:
    branches: [webservice]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: webservice

    steps:
      - name: Trigger deployment on Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK
