name: Validate Secrets

on: [push, pull_request]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Validate required secrets
        run: |
          MISSING_SECRETS=0

          if [ -z "${{ secrets.DISCORD_TOKEN }}" ]; then
            echo "Error: Missing required secret DISCORD_TOKEN"
            MISSING_SECRETS=1
          else
            echo "DISCORD_TOKEN is set"
          fi

          if [ -z "${{ secrets.CLIENT_ID }}" ]; then
            echo "Error: Missing required secret CLIENT_ID"
            MISSING_SECRETS=1
          else
            echo "CLIENT_ID is set"
          fi

          if [ -z "${{ secrets.CHANNEL_ID }}" ]; then
            echo "Error: Missing required secret CHANNEL_ID"
            MISSING_SECRETS=1
          else
            echo "CHANNEL_ID is set"
          fi

          if [ -z "${{ secrets.RSS_FEED_URL }}" ]; then
            echo "Error: Missing required secret RSS_FEED_URL"
            MISSING_SECRETS=1
          else
            echo "RSS_FEED_URL is set"
          fi

          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "Error: Missing required secret RENDER_DEPLOY_HOOK"
            MISSING_SECRETS=1
          else
            echo "RENDER_DEPLOY_HOOK is set"
          fi

          if [ "$MISSING_SECRETS" -eq 1 ]; then
            exit 1
          fi
