name: Validate Secrets

on: [push, pull_request]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Validate required secrets
        run: |
          REQUIRED_SECRETS=("DISCORD_TOKEN" "CLIENT_ID" "CHANNEL_ID" "RSS_FEED_URL" "RENDER_DEPLOY_HOOK")
          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[${secret}] }}" ]; then
              echo "Error: Missing required secret $secret"
              exit 1
            else
              echo "$secret is set"
            fi
          done
